const componentsData = {
    cpus: [
        { id: 1, name: 'Intel Core i9-14900KS', socket: 'LGA1700', tdp: 253, price: 750, types: ['gaming', 'streaming', 'workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/cpu/i9-14900ks' },
        { id: 2, name: 'Intel Core i9-14900KF', socket: 'LGA1700', tdp: 253, price: 480, types: ['gaming', 'streaming', 'workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/cpu/i9-14900kf' },
        { id: 3, name: 'Intel Core i9-14900K', socket: 'LGA1700', tdp: 253, price: 520, types: ['gaming', 'streaming', 'workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/cpu/i9-14900k' },
        { id: 4, name: 'Intel Core i9-13900K', socket: 'LGA1700', tdp: 253, price: 400, types: ['gaming', 'streaming', 'workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/cpu/i9-13900k' },
        { id: 5, name: 'Intel Core i7-14700K', socket: 'LGA1700', tdp: 125, price: 350, types: ['gaming', 'streaming', 'workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/cpu/i7-14700k' },
        { id: 6, name: 'Intel Core i7-14700KF', socket: 'LGA1700', tdp: 125, price: 320, types: ['gaming', 'streaming', 'workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/cpu/i7-14700kf' },
        { id: 7, name: 'Intel Core i7-13700K', socket: 'LGA1700', tdp: 125, price: 280, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/cpu/i7-13700k' },
        { id: 8, name: 'Intel Core i5-14600K', socket: 'LGA1700', tdp: 125, price: 240, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/cpu/i5-14600k' },
        { id: 9, name: 'Intel Core i5-14600KF', socket: 'LGA1700', tdp: 125, price: 220, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/cpu/i5-14600kf' },
        { id: 10, name: 'Intel Core i5-13600K', socket: 'LGA1700', tdp: 125, price: 180, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/cpu/i5-13600k' },
        { id: 11, name: 'Intel Core i5-14600', socket: 'LGA1700', tdp: 65, price: 180, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/cpu/i5-14600' },
        { id: 12, name: 'Intel Core i5-13600', socket: 'LGA1700', tdp: 65, price: 160, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/cpu/i5-13600' },
        { id: 13, name: 'Intel Core i3-14100', socket: 'LGA1700', tdp: 42, price: 80, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/cpu/i3-14100' },
        { id: 14, name: 'Intel Core i3-13100', socket: 'LGA1700', tdp: 42, price: 65, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/cpu/i3-13100' },
        { id: 15, name: 'Intel Core i3-12100', socket: 'LGA1700', tdp: 35, price: 50, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/cpu/i3-12100' },
        { id: 16, name: 'Intel Celeron G6900', socket: 'LGA1700', tdp: 35, price: 35, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/cpu/g6900' },
        { id: 17, name: 'AMD Ryzen 3 4100', socket: 'AM4', tdp: 35, price: 40, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/cpu/ryzen-3-4100' },
        { id: 18, name: 'AMD Ryzen 9 7950X3D', socket: 'AM5', tdp: 162, price: 550, types: ['gaming', 'streaming', 'workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/cpu/ryzen-9-7950x3d' },
        { id: 19, name: 'AMD Ryzen 9 7950X', socket: 'AM5', tdp: 162, price: 480, types: ['gaming', 'streaming', 'workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/cpu/ryzen-9-7950x' },
        { id: 20, name: 'AMD Ryzen 9 9900X', socket: 'AM5', tdp: 120, price: 420, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/cpu/ryzen-9-9900x' },
        { id: 21, name: 'AMD Ryzen 9 5950X', socket: 'AM4', tdp: 105, price: 400, types: ['gaming', 'streaming', 'workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/cpu/ryzen-9-5950x' },
        { id: 22, name: 'AMD Ryzen 7 7700X', socket: 'AM5', tdp: 105, price: 280, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/cpu/ryzen-7-7700x' },
        { id: 23, name: 'AMD Ryzen 7 7700', socket: 'AM5', tdp: 65, price: 220, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/cpu/ryzen-7-7700' },
        { id: 24, name: 'AMD Ryzen 7 9700X', socket: 'AM5', tdp: 105, price: 340, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/cpu/ryzen-7-9700x' },
        { id: 25, name: 'AMD Ryzen 5 7600X', socket: 'AM5', tdp: 105, price: 160, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/cpu/ryzen-5-7600x' },
        { id: 26, name: 'AMD Ryzen 5 7600', socket: 'AM5', tdp: 65, price: 140, types: ['gaming', 'office', 'budget'], affiliateLink: 'https://affiliate.example.com/cpu/ryzen-5-7600' },
        { id: 27, name: 'AMD Ryzen 5 5600X', socket: 'AM4', tdp: 65, price: 150, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/cpu/ryzen-5-5600x' },
        { id: 28, name: 'AMD Ryzen 5 5500', socket: 'AM4', tdp: 65, price: 90, types: ['gaming', 'office', 'budget'], affiliateLink: 'https://affiliate.example.com/cpu/ryzen-5-5500' },
        { id: 29, name: 'Intel Xeon W9-3495X', socket: 'LGA4677', tdp: 350, price: 3200, types: ['workstation'], affiliateLink: 'https://affiliate.example.com/cpu/xeon-w9' },
        { id: 30, name: 'Intel Xeon W7-2495X', socket: 'LGA4677', tdp: 250, price: 2400, types: ['workstation'], affiliateLink: 'https://affiliate.example.com/cpu/xeon-w7' },
        { id: 31, name: 'AMD Ryzen Threadripper 7980X', socket: 'TRX40', tdp: 320, price: 3500, types: ['workstation'], affiliateLink: 'https://affiliate.example.com/cpu/threadripper-7980x' },
        { id: 32, name: 'AMD Ryzen Threadripper 5990X', socket: 'TRX40', tdp: 280, price: 2900, types: ['workstation'], affiliateLink: 'https://affiliate.example.com/cpu/threadripper-5990x' },
    ],
    
    mainboards: [
        { id: 1, name: 'ASUS ROG STRIX Z790-E Gaming WiFi', socket: 'LGA1700', ramType: 'DDR5', maxRam: 192, psuType: 'ATX', price: 420, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/mb/z790-e' },
        { id: 2, name: 'MSI MPG Z790 Edge WiFi', socket: 'LGA1700', ramType: 'DDR5', maxRam: 192, psuType: 'ATX', price: 380, types: ['gaming', 'creator'], affiliateLink: 'https://affiliate.example.com/mb/z790-edge' },
        { id: 3, name: 'Gigabyte Z790 AORUS Master', socket: 'LGA1700', ramType: 'DDR5', maxRam: 192, psuType: 'ATX', price: 390, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/mb/z790-master' },
        { id: 4, name: 'ASUS TUF Z790-Pro WiFi', socket: 'LGA1700', ramType: 'DDR5', maxRam: 192, psuType: 'ATX', price: 350, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/mb/z790-pro' },
        { id: 5, name: 'MSI MPG Z790 Carbon WiFi', socket: 'LGA1700', ramType: 'DDR5', maxRam: 192, psuType: 'ATX', price: 370, types: ['gaming', 'creator'], affiliateLink: 'https://affiliate.example.com/mb/z790-carbon' },
        { id: 6, name: 'ASUS TUF B660-Plus WiFi', socket: 'LGA1700', ramType: 'DDR4', maxRam: 128, psuType: 'ATX', price: 180, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/mb/b660-plus' },
        { id: 7, name: 'Gigabyte B760 AORUS Pro', socket: 'LGA1700', ramType: 'DDR5', maxRam: 192, psuType: 'ATX', price: 200, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/mb/b760-pro' },
        { id: 8, name: 'ASRock B760M Pro RS', socket: 'LGA1700', ramType: 'DDR4', maxRam: 128, psuType: 'Micro-ATX', price: 120, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/mb/b760m-pro' },
        { id: 9, name: 'ASUS ROG STRIX X870-E Gaming WiFi', socket: 'AM5', ramType: 'DDR5', maxRam: 192, psuType: 'ATX', price: 450, types: ['gaming', 'streaming', 'workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/mb/x870-e' },
        { id: 10, name: 'MSI MPG X870E-E Gaming WiFi', socket: 'AM5', ramType: 'DDR5', maxRam: 192, psuType: 'ATX', price: 470, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/mb/x870e-e' },
        { id: 11, name: 'ASUS TUF X870-E Gaming WiFi', socket: 'AM5', ramType: 'DDR5', maxRam: 192, psuType: 'ATX', price: 480, types: ['gaming', 'workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/mb/x870-e-tuf' },
        { id: 12, name: 'Gigabyte X870E AORUS Master', socket: 'AM5', ramType: 'DDR5', maxRam: 192, psuType: 'ATX', price: 460, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/mb/x870e-master' },
        { id: 13, name: 'MSI MPG B550 Edge WiFi', socket: 'AM4', ramType: 'DDR4', maxRam: 128, psuType: 'ATX', price: 150, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/mb/b550-edge' },
        { id: 14, name: 'ASUS ROG STRIX B550-I Gaming WiFi', socket: 'AM4', ramType: 'DDR4', maxRam: 128, psuType: 'SFX', price: 200, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/mb/b550-i' },
        { id: 15, name: 'Gigabyte B550 AORUS Pro', socket: 'AM4', ramType: 'DDR4', maxRam: 128, psuType: 'ATX', price: 140, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/mb/b550-pro' },
        { id: 16, name: 'ASRock H610M Phantom Gaming', socket: 'LGA1700', ramType: 'DDR4', maxRam: 64, psuType: 'Micro-ATX', price: 85, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/mb/h610m-phantom' },
        { id: 17, name: 'MSI PRO H610M-E', socket: 'LGA1700', ramType: 'DDR4', maxRam: 64, psuType: 'Micro-ATX', price: 90, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/mb/h610m-e' },
        { id: 18, name: 'ASRock A520M-ITX/TB3', socket: 'AM4', ramType: 'DDR4', maxRam: 64, psuType: 'Micro-ATX', price: 75, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/mb/a520m-itx' },
        { id: 19, name: 'Gigabyte A520M DS3H', socket: 'AM4', ramType: 'DDR4', maxRam: 64, psuType: 'Micro-ATX', price: 65, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/mb/a520m-dsh' },
    ],
    
    rams: [
        { id: 1, name: 'Corsair Vengeance DDR5 6000MHz 32GB', type: 'DDR5', capacity: 32, speed: 6000, price: 160, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/ram/ddr5-6000-32gb' },
        { id: 2, name: 'Corsair Vengeance DDR5 6000MHz 64GB', type: 'DDR5', capacity: 64, speed: 6000, price: 300, types: ['gaming', 'workstation', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/ram/ddr5-6000-64gb' },
        { id: 3, name: 'Corsair Vengeance DDR5 6000MHz 96GB', type: 'DDR5', capacity: 96, speed: 6000, price: 420, types: ['workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/ram/ddr5-6000-96gb' },
        { id: 4, name: 'G.Skill Trident Z5 DDR5 6400MHz 32GB', type: 'DDR5', capacity: 32, speed: 6400, price: 170, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/ram/ddr5-6400-32gb' },
        { id: 5, name: 'G.Skill Trident Z5 DDR5 6400MHz 64GB', type: 'DDR5', capacity: 64, speed: 6400, price: 320, types: ['gaming', 'workstation', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/ram/ddr5-6400-64gb' },
        { id: 6, name: 'Kingston Fury DDR5 5600MHz 32GB', type: 'DDR5', capacity: 32, speed: 5600, price: 150, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/ram/ddr5-5600-32gb' },
        { id: 7, name: 'Kingston Fury DDR5 6000MHz 64GB', type: 'DDR5', capacity: 64, speed: 6000, price: 280, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/ram/ddr5-6000-64gb-kingston' },
        { id: 8, name: 'ADATA XPG LIAN XL DDR5 7200MHz 32GB', type: 'DDR5', capacity: 32, speed: 7200, price: 200, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/ram/lian-7200-32gb' },
        { id: 9, name: 'Corsair Vengeance DDR4 3600MHz 32GB', type: 'DDR4', capacity: 32, speed: 3600, price: 110, types: ['gaming', 'office'], affiliateLink: 'https://affiliate.example.com/ram/ddr4-3600-32gb' },
        { id: 10, name: 'Corsair Vengeance DDR4 3600MHz 64GB', type: 'DDR4', capacity: 64, speed: 3600, price: 200, types: ['office', 'workstation'], affiliateLink: 'https://affiliate.example.com/ram/ddr4-3600-64gb' },
        { id: 11, name: 'G.Skill Flare X DDR4 3200MHz 32GB', type: 'DDR4', capacity: 32, speed: 3200, price: 100, types: ['gaming', 'office', 'budget'], affiliateLink: 'https://affiliate.example.com/ram/ddr4-3200-32gb' },
        { id: 12, name: 'Kingston Fury DDR4 3200MHz 16GB', type: 'DDR4', capacity: 16, speed: 3200, price: 55, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/ram/ddr4-3200-16gb' },
        { id: 13, name: 'Kingston Fury DDR4 3200MHz 32GB', type: 'DDR4', capacity: 32, speed: 3200, price: 95, types: ['gaming', 'office', 'budget'], affiliateLink: 'https://affiliate.example.com/ram/ddr4-3200-32gb-kingston' },
        { id: 14, name: 'Corsair Vengeance DDR4 3200MHz 16GB', type: 'DDR4', capacity: 16, speed: 3200, price: 50, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/ram/ddr4-3200-16gb-corsair' },
        { id: 15, name: 'G.Skill Trident Z5 DDR5 7200MHz 48GB', type: 'DDR5', capacity: 48, speed: 7200, price: 280, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/ram/ddr5-7200-48gb' },
        { id: 16, name: 'Kingston Fury DDR4 3200MHz 8GB', type: 'DDR4', capacity: 8, speed: 3200, price: 30, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/ram/ddr4-3200-8gb' },
        { id: 17, name: 'Corsair Vengeance DDR4 3200MHz 8GB', type: 'DDR4', capacity: 8, speed: 3200, price: 28, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/ram/ddr4-3200-8gb-corsair' },
        { id: 18, name: 'G.Skill Flare X DDR4 3200MHz 16GB', type: 'DDR4', capacity: 16, speed: 3200, price: 55, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/ram/ddr4-3200-16gb-gskill' },
    ],
    
    gpus: [
        { id: 1, name: 'NVIDIA RTX 4090', power: 450, length: 375, price: 1600, types: ['gaming', 'streaming', 'workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/gpu/rtx-4090' },
        { id: 2, name: 'NVIDIA RTX 4090 D', power: 500, length: 350, price: 6800, types: ['workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/gpu/rtx-4090d' },
        { id: 3, name: 'NVIDIA RTX 4080 Super', power: 320, length: 360, price: 1200, types: ['gaming', 'streaming', 'workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/gpu/rtx-4080s' },
        { id: 4, name: 'NVIDIA RTX 4080', power: 320, length: 360, price: 1000, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/gpu/rtx-4080' },
        { id: 5, name: 'NVIDIA RTX 4070 Ti', power: 285, length: 335, price: 900, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/gpu/rtx-4070ti' },
        { id: 6, name: 'NVIDIA RTX 4070 Ti SUPER', power: 285, length: 355, price: 950, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/gpu/rtx-4070ti-super' },
        { id: 7, name: 'NVIDIA RTX 4070', power: 200, length: 310, price: 700, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/gpu/rtx-4070' },
        { id: 8, name: 'NVIDIA RTX 4070 SUPER', power: 220, length: 320, price: 750, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/gpu/rtx-4070-super' },
        { id: 9, name: 'NVIDIA RTX 4060 Ti', power: 130, length: 255, price: 380, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/gpu/rtx-4060ti' },
        { id: 10, name: 'NVIDIA RTX 4060', power: 70, length: 240, price: 240, types: ['gaming', 'budget', 'office'], affiliateLink: 'https://affiliate.example.com/gpu/rtx-4060' },
        { id: 11, name: 'NVIDIA RTX 4050', power: 70, length: 220, price: 180, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/gpu/rtx-4050' },
        { id: 12, name: 'AMD Radeon RX 7900 XTX', power: 420, length: 385, price: 1250, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/gpu/rx-7900xtx' },
        { id: 13, name: 'AMD Radeon RX 7900 XT', power: 420, length: 380, price: 800, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/gpu/rx-7900xt' },
        { id: 14, name: 'AMD Radeon RX 7800 XT', power: 320, length: 320, price: 500, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/gpu/rx-7800xt' },
        { id: 15, name: 'AMD Radeon RX 7700 XT', power: 250, length: 280, price: 350, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/gpu/rx-7700xt' },
        { id: 16, name: 'AMD Radeon RX 7600', power: 150, length: 280, price: 220, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/gpu/rx-7600' },
        { id: 17, name: 'Intel Arc A770 16GB', power: 225, length: 300, price: 350, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/gpu/arc-a770' },
        { id: 18, name: 'Intel Arc A750', power: 130, length: 250, price: 200, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/gpu/arc-a750' },
        { id: 19, name: 'Intel Arc A380', power: 75, length: 220, price: 100, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/gpu/arc-a380' },
        { id: 20, name: 'No GPU (iGPU)', power: 0, length: 0, price: 0, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/gpu/no-gpu' },
        { id: 21, name: 'AMD Radeon RX 6600', power: 150, length: 250, price: 150, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/gpu/rx-6600' },
        { id: 22, name: 'NVIDIA GT 1030', power: 30, length: 180, price: 80, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/gpu/gt-1030' },
    ],
    
    psus: [
        { id: 1, name: 'Corsair RM1200x 1200W', wattage: 1200, type: 'ATX', price: 220, types: ['gaming', 'streaming', 'workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/psu/rm1200x' },
        { id: 2, name: 'Corsair RM1000x 1000W', wattage: 1000, type: 'ATX', price: 180, types: ['gaming', 'streaming', 'workstation'], affiliateLink: 'https://affiliate.example.com/psu/rm1000x' },
        { id: 3, name: 'Corsair HX1500i 1500W', wattage: 1500, type: 'ATX', price: 320, types: ['gaming', 'streaming', 'workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/psu/hx1500i' },
        { id: 4, name: 'Corsair HX1000 1000W', wattage: 1000, type: 'ATX', price: 200, types: ['gaming', 'streaming', 'workstation'], affiliateLink: 'https://affiliate.example.com/psu/hx1000' },
        { id: 5, name: 'MSI MPG A850GF 850W', wattage: 850, type: 'ATX', price: 130, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/psu/a850gf' },
        { id: 6, name: 'MSI MPG A750GF 750W', wattage: 750, type: 'ATX', price: 120, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/psu/a750gf' },
        { id: 7, name: 'EVGA SuperNOVA 1000 GT 1000W', wattage: 1000, type: 'ATX', price: 180, types: ['gaming', 'streaming', 'workstation'], affiliateLink: 'https://affiliate.example.com/psu/1000gt' },
        { id: 8, name: 'EVGA SuperNOVA 850 GA 850W', wattage: 850, type: 'ATX', price: 140, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/psu/850ga' },
        { id: 9, name: 'Seasonic Prime Ultra 1000W', wattage: 1000, type: 'ATX', price: 190, types: ['gaming', 'streaming', 'workstation'], affiliateLink: 'https://affiliate.example.com/psu/prime-1000' },
        { id: 10, name: 'Seasonic Focus Plus 850W', wattage: 850, type: 'ATX', price: 125, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/psu/focus-850' },
        { id: 11, name: 'Seasonic Focus Plus 650W', wattage: 650, type: 'ATX', price: 100, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/psu/focus-650' },
        { id: 12, name: 'Be Quiet! Straight Power 12 750W', wattage: 750, type: 'ATX', price: 115, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/psu/sp12-750' },
        { id: 13, name: 'Be Quiet! System Power 500W', wattage: 500, type: 'ATX', price: 65, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/psu/bq-500' },
        { id: 14, name: 'Corsair SF750 750W', wattage: 750, type: 'SFX', price: 180, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/psu/sf750' },
        { id: 15, name: 'Silverstone SX500-LG 500W', wattage: 500, type: 'SFX', price: 100, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/psu/sx500-lg' },
        { id: 16, name: 'Gigabyte UD1200GM 1200W', wattage: 1200, type: 'ATX', price: 200, types: ['gaming', 'streaming', 'workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/psu/ud1200gm' },
        { id: 17, name: 'Gigabyte UD850GM 850W', wattage: 850, type: 'ATX', price: 130, types: ['gaming', 'workstation'], affiliateLink: 'https://affiliate.example.com/psu/ud850gm' },
        { id: 18, name: 'Be Quiet! System Power 350W', wattage: 350, type: 'ATX', price: 45, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/psu/bq-350' },
        { id: 19, name: 'Seasonic S12II-430', wattage: 430, type: 'ATX', price: 55, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/psu/s12ii-430' },
        { id: 20, name: 'MSI MAG A550GL 550W', wattage: 550, type: 'ATX', price: 75, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/psu/a550gl' },
    ],
    
    storages: [
        { id: 1, name: 'Samsung 990 Pro 2TB NVMe', type: 'NVMe', capacity: 2000, price: 180, types: ['gaming', 'streaming', 'workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/storage/990pro-2tb' },
        { id: 2, name: 'Samsung 990 Pro 4TB NVMe', type: 'NVMe', capacity: 4000, price: 350, types: ['gaming', 'streaming', 'workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/storage/990pro-4tb' },
        { id: 3, name: 'Samsung 990 Pro 8TB NVMe', type: 'NVMe', capacity: 8000, price: 680, types: ['workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/storage/990pro-8tb' },
        { id: 4, name: 'WD Black SN850X 1TB', type: 'NVMe', capacity: 1000, price: 120, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/storage/sn850x-1tb' },
        { id: 5, name: 'WD Black SN850X 2TB', type: 'NVMe', capacity: 2000, price: 220, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/storage/sn850x-2tb' },
        { id: 6, name: 'WD Black SN850X 4TB', type: 'NVMe', capacity: 4000, price: 420, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/storage/sn850x-4tb' },
        { id: 7, name: 'Kingston KC3000 2TB', type: 'NVMe', capacity: 2000, price: 160, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/storage/kc3000-2tb' },
        { id: 8, name: 'Kingston NV2 1TB', type: 'NVMe', capacity: 1000, price: 80, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/storage/nv2-1tb' },
        { id: 9, name: 'Kingston NV2 2TB', type: 'NVMe', capacity: 2000, price: 150, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/storage/nv2-2tb' },
        { id: 10, name: 'Sabrent Rocket Plus 2TB NVMe', type: 'NVMe', capacity: 2000, price: 140, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/storage/rocket-2tb' },
        { id: 11, name: 'Seagate Barracuda 4TB HDD', type: 'HDD', capacity: 4000, price: 80, types: ['office', 'workstation', 'budget'], affiliateLink: 'https://affiliate.example.com/storage/barracuda-4tb' },
        { id: 12, name: 'Seagate Barracuda 2TB HDD', type: 'HDD', capacity: 2000, price: 50, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/storage/barracuda-2tb' },
        { id: 13, name: 'WD Blue 2TB HDD', type: 'HDD', capacity: 2000, price: 55, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/storage/blue-2tb' },
        { id: 14, name: 'WD Blue 1TB HDD', type: 'HDD', capacity: 1000, price: 30, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/storage/blue-1tb' },
        { id: 15, name: 'Samsung 870 EVO 2TB SSD', type: 'SATA', capacity: 2000, price: 140, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/storage/870evo-2tb' },
        { id: 16, name: 'Samsung 870 EVO 1TB SSD', type: 'SATA', capacity: 1000, price: 70, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/storage/870evo-1tb' },
        { id: 17, name: 'Kingston NV2 512GB', type: 'NVMe', capacity: 512, price: 45, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/storage/nv2-512gb' },
        { id: 18, name: 'Seagate Barracuda 1TB HDD', type: 'HDD', capacity: 1000, price: 25, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/storage/barracuda-1tb' },
        { id: 19, name: 'WD Blue 512GB SSD', type: 'SATA', capacity: 512, price: 35, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/storage/blue-512gb' },
    ],
    
    cases: [
        { id: 1, name: 'Lian Li O11 Dynamic', maxGpuLength: 420, maxCoolerHeight: 180, psuType: 'ATX', price: 150, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/case/o11-dynamic' },
        { id: 2, name: 'Lian Li O11 Dynamic EVO', maxGpuLength: 420, maxCoolerHeight: 180, psuType: 'ATX', price: 180, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/case/o11-evo' },
        { id: 3, name: 'Corsair Crystal 570X RGB', maxGpuLength: 370, maxCoolerHeight: 160, psuType: 'ATX', price: 180, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/case/570x' },
        { id: 4, name: 'Corsair 5000D Airflow', maxGpuLength: 390, maxCoolerHeight: 170, psuType: 'ATX', price: 160, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/case/5000d' },
        { id: 5, name: 'Corsair 5000T RGB', maxGpuLength: 390, maxCoolerHeight: 170, psuType: 'ATX', price: 200, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/case/5000t' },
        { id: 6, name: 'NZXT H510 Flow', maxGpuLength: 330, maxCoolerHeight: 165, psuType: 'ATX', price: 110, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/case/h510-flow' },
        { id: 7, name: 'NZXT H710i', maxGpuLength: 370, maxCoolerHeight: 160, psuType: 'ATX', price: 200, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/case/h710i' },
        { id: 8, name: 'Phanteks Eclipse P500A', maxGpuLength: 330, maxCoolerHeight: 180, psuType: 'ATX', price: 140, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/case/p500a' },
        { id: 9, name: 'Phanteks Eclipse P600S', maxGpuLength: 370, maxCoolerHeight: 160, psuType: 'ATX', price: 160, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/case/p600s' },
        { id: 10, name: 'Lian Li Q58', maxGpuLength: 280, maxCoolerHeight: 120, psuType: 'SFX', price: 130, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/case/q58' },
        { id: 11, name: 'Corsair Crystal 280X RGB', maxGpuLength: 310, maxCoolerHeight: 150, psuType: 'SFX', price: 150, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/case/280x' },
        { id: 12, name: 'Fractal Design Core 1000', maxGpuLength: 350, maxCoolerHeight: 160, psuType: 'ATX', price: 50, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/case/core1000' },
        { id: 13, name: 'Cooler Master Hyper 212 LED', maxGpuLength: 380, maxCoolerHeight: 180, psuType: 'ATX', price: 85, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/case/hyper212' },
        { id: 14, name: 'Fractal Design Meshify 2', maxGpuLength: 380, maxCoolerHeight: 185, psuType: 'ATX', price: 150, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/case/meshify-2' },
        { id: 15, name: 'Cooler Master TD500 Mesh', maxGpuLength: 370, maxCoolerHeight: 160, psuType: 'ATX', price: 140, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/case/td500-mesh' },
        { id: 16, name: 'Fractal Design Core 1000 Micro', maxGpuLength: 280, maxCoolerHeight: 160, psuType: 'SFX', price: 40, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/case/core1000-micro' },
        { id: 17, name: 'Cooler Master N200', maxGpuLength: 320, maxCoolerHeight: 160, psuType: 'ATX', price: 50, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/case/n200' },
        { id: 18, name: 'Thermaltake Versa H15', maxGpuLength: 300, maxCoolerHeight: 150, psuType: 'ATX', price: 45, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/case/versa-h15' },
    ],
    
    coolers: [
        { id: 1, name: 'Noctua NH-D15', height: 160, tdpRating: 250, price: 90, types: ['gaming', 'office', 'workstation'], affiliateLink: 'https://affiliate.example.com/cooler/nh-d15' },
        { id: 2, name: 'Noctua NH-D15 SE-AM5', height: 160, tdpRating: 250, price: 95, types: ['gaming', 'streaming', 'workstation'], affiliateLink: 'https://affiliate.example.com/cooler/nh-d15-se-am5' },
        { id: 3, name: 'Noctua NH-U14S', height: 165, tdpRating: 220, price: 75, types: ['gaming', 'office'], affiliateLink: 'https://affiliate.example.com/cooler/nh-u14s' },
        { id: 4, name: 'Noctua NH-U12S', height: 158, tdpRating: 220, price: 65, types: ['gaming', 'office', 'budget'], affiliateLink: 'https://affiliate.example.com/cooler/nh-u12s' },
        { id: 5, name: 'Be Quiet Dark Rock Pro 4', height: 162, tdpRating: 250, price: 85, types: ['gaming', 'office'], affiliateLink: 'https://affiliate.example.com/cooler/drp4' },
        { id: 6, name: 'Be Quiet Dark Rock Elite', height: 163, tdpRating: 280, price: 60, types: ['gaming', 'office', 'budget'], affiliateLink: 'https://affiliate.example.com/cooler/dre' },
        { id: 7, name: 'Corsair H150i Elite Capellix', height: 120, tdpRating: 300, price: 200, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/cooler/h150i' },
        { id: 8, name: 'Corsair H100i Elite Capellix', height: 110, tdpRating: 280, price: 150, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/cooler/h100i' },
        { id: 9, name: 'NZXT Kraken X93', height: 110, tdpRating: 320, price: 180, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/cooler/kraken-x93' },
        { id: 10, name: 'NZXT Kraken Z73', height: 110, tdpRating: 320, price: 220, types: ['gaming', 'streaming', 'creator'], affiliateLink: 'https://affiliate.example.com/cooler/kraken-z73' },
        { id: 11, name: 'Thermalright Peerless Assassin 120 SE', height: 155, tdpRating: 280, price: 35, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/cooler/pa120se' },
        { id: 12, name: 'Scythe Mugen 5 Rev. B', height: 154, tdpRating: 250, price: 50, types: ['gaming', 'office', 'budget'], affiliateLink: 'https://affiliate.example.com/cooler/mugen5' },
        { id: 13, name: 'Arctic Freezer 34 eSports DUO', height: 157, tdpRating: 240, price: 40, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/cooler/freezer-34' },
        { id: 14, name: 'Thermalright Shade 1', height: 165, tdpRating: 260, price: 50, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/cooler/shade-1' },
        { id: 15, name: 'Corsair H170i Elite Capellix', height: 120, tdpRating: 350, price: 240, types: ['gaming', 'streaming', 'workstation', 'creator'], affiliateLink: 'https://affiliate.example.com/cooler/h170i' },
        { id: 16, name: 'Stock Intel Cooler', height: 50, tdpRating: 65, price: 0, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/cooler/stock-intel' },
        { id: 17, name: 'Stock AMD Cooler', height: 50, tdpRating: 65, price: 0, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/cooler/stock-amd' },
        { id: 18, name: 'Deepcool AK400', height: 159, tdpRating: 240, price: 22, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/cooler/ak400' },
        { id: 19, name: 'Jonsbo HX-223', height: 157, tdpRating: 220, price: 25, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/cooler/hx-223' },
    ],

    accessories: [
        { id: 1, name: 'HDMI Kabel 2.1 (2m)', type: 'Kabel', price: 15, types: ['gaming', 'office', 'streaming', 'workstation', 'creator', 'budget'], description: 'Hochwertiges HDMI 2.1 Kabel mit voller Unterstützung für 8K, HDR und hohe Bildwiederholfrequenzen. Ideal für Gaming und 4K Streaming.', affiliateLink: 'https://affiliate.example.com/acc/hdmi-2m' },
        { id: 2, name: 'DisplayPort 1.4 Kabel (2m)', type: 'Kabel', price: 18, types: ['gaming', 'streaming', 'creator', 'workstation'], description: 'DisplayPort 1.4 mit 32.4 Gbps Bandbreite. Unterstützt 8K@60Hz und 4K@120Hz. Perfekt für Gaming und Content Creation.', affiliateLink: 'https://affiliate.example.com/acc/dp-2m' },
        { id: 3, name: 'USB-C Kabel (3m)', type: 'Kabel', price: 12, types: ['gaming', 'office', 'streaming', 'creator', 'budget'], description: 'Robustes USB-C Kabel mit bis zu 100W Schnellladung. Ideal für externe Festplatten, Monitore und Zubehör.', affiliateLink: 'https://affiliate.example.com/acc/usb-c-3m' },
        { id: 4, name: 'Stromkabel Set (3er Pack)', type: 'Kabel', price: 20, types: ['gaming', 'office', 'streaming', 'workstation', 'creator', 'budget'], description: 'Premium Stromkabel Set mit 3 verschiedenen Längen. Hochwertige Ummantelung und optimale Sicherheit für alle Komponenten.', affiliateLink: 'https://affiliate.example.com/acc/power-cables' },
        { id: 5, name: 'Ethernet Kabel Cat.8 (5m)', type: 'Kabel', price: 25, types: ['gaming', 'streaming', 'office', 'creator'], description: 'Cat.8 Ethernet Kabel mit bis zu 40 Gbps. Ideal für schnelle LAN-Verbindungen und stabiles Gaming ohne Lag.', affiliateLink: 'https://affiliate.example.com/acc/ethernet-5m' },
        { id: 6, name: 'Kabelorganizer Set', type: 'Zubehör', price: 15, types: ['gaming', 'office', 'streaming', 'workstation', 'creator', 'budget'], description: 'Umfassendes Kabelorganizer Set mit verschiedenen Größen. Hält alle Kabel ordentlich und schützt vor Beschädigungen.', affiliateLink: 'https://affiliate.example.com/acc/cable-organizer' },
        { id: 7, name: 'Gaming Monitor 144Hz 27" 1440p', type: 'Monitor', price: 350, types: ['gaming', 'streaming'], description: '27" IPS Monitor mit 2560x1440 Auflösung und 144Hz Bildwiederholfrequenz. Optimiert für kompetitives Gaming und Streaming.', affiliateLink: 'https://affiliate.example.com/acc/monitor-144hz' },
        { id: 8, name: 'Gaming Monitor 165Hz 27" 1440p', type: 'Monitor', price: 400, types: ['gaming', 'streaming'], description: '27" Gaming Monitor mit 165Hz und 1ms Reaktionszeit. Perfekt für Esports und schnellpaced Spiele mit scharfen Bildern.', affiliateLink: 'https://affiliate.example.com/acc/monitor-165hz' },
        { id: 9, name: '4K Monitor 27" 60Hz IPS', type: 'Monitor', price: 450, types: ['creator', 'workstation', 'streaming'], description: '27" UHD Monitor mit 3840x2160 Auflösung und 100% sRGB. Ideal für Farbkorrekturen und Videobearbeitung.', affiliateLink: 'https://affiliate.example.com/acc/monitor-4k' },
        { id: 10, name: 'Office Monitor 24" Full-HD IPS', type: 'Monitor', price: 150, types: ['office', 'budget'], description: '24" Full-HD IPS Monitor mit blendfreiem Panel und flackerfreier Technologie. Ideal für lange Arbeitszeiten im Büro.', affiliateLink: 'https://affiliate.example.com/acc/monitor-fhd' },
        { id: 11, name: 'Mechanische Gaming Tastatur RGB', type: 'Tastatur', price: 80, types: ['gaming', 'streaming', 'creator'], description: 'Gaming Tastatur mit mechanischen Schaltern, RGB Beleuchtung und Makros. Langlebig und responsive für kompetitives Gaming.', affiliateLink: 'https://affiliate.example.com/acc/mech-kb' },
        { id: 12, name: 'Office Tastatur kabellos', type: 'Tastatur', price: 40, types: ['office', 'budget'], description: 'Kabellose Tastatur mit 2,4 GHz Technologie. Leise Tasten und lange Akkulaufzeit für produktive Arbeitstage.', affiliateLink: 'https://affiliate.example.com/acc/office-kb' },
        { id: 13, name: 'Gaming Maus RGB 16000 DPI', type: 'Maus', price: 60, types: ['gaming', 'streaming'], description: 'Gaming Maus mit bis zu 16000 DPI, 8 programmierbaren Tasten und ergonomischem Griff. Perfekt für alle Spielgenres.', affiliateLink: 'https://affiliate.example.com/acc/gaming-mouse' },
        { id: 14, name: 'Ergonomische Office Maus', type: 'Maus', price: 35, types: ['office', 'budget'], description: 'Ergonomische vertikale Maus zur Vermeidung von Sehnenentzündungen. Kabellos und komfortable für lange Arbeitstage.', affiliateLink: 'https://affiliate.example.com/acc/office-mouse' },
        { id: 15, name: 'Gaming Headset mit Mikrofon', type: 'Headset', price: 120, types: ['gaming', 'streaming'], description: 'Gaming Headset mit 7.1 Surround Sound und Rauschunterdrückungsmikrofon. Perfekt für Online-Spiele und Teamkommunikation.', affiliateLink: 'https://affiliate.example.com/acc/gaming-headset' },
        { id: 16, name: 'Wireless Headphones Studio', type: 'Headset', price: 250, types: ['creator', 'workstation', 'streaming'], description: 'Studio-Kopfhörer mit aktiver Geräuschunterdrückung und Bluetooth 5.0. Ideal für Audio-Bearbeitung und Musik-Produktion.', affiliateLink: 'https://affiliate.example.com/acc/wireless-headset' },
        { id: 17, name: 'USB Hub 3.0 7-Port', type: 'Zubehör', price: 30, types: ['gaming', 'office', 'streaming', 'creator', 'budget'], description: 'USB 3.0 Hub mit 7 Anschlüssen und Stromversorgung. Erweitert die USB-Konnektivität ohne Leistungsverlust.', affiliateLink: 'https://affiliate.example.com/acc/usb-hub' },
        { id: 18, name: 'Gaming Mousepad XXL RGB', type: 'Zubehör', price: 50, types: ['gaming', 'streaming'], description: 'Großes Gaming Mousepad (800x300mm) mit RGB Beleuchtung und rutschfester Basis. Optimiert für Gaming Mäuse und trägt lange.', affiliateLink: 'https://affiliate.example.com/acc/mousepad-xxl' },
        { id: 19, name: 'Monitor Arm Halterung', type: 'Zubehör', price: 60, types: ['gaming', 'office', 'streaming', 'creator', 'workstation'], description: 'Verstellbare Monitor-Halterung für 17-32" Monitore. Spart Platz und ermöglicht optimale Blickwinkel für ergonomische Arbeit.', affiliateLink: 'https://affiliate.example.com/acc/monitor-arm' },
        { id: 20, name: 'Webcam 4K mit Autofokus', type: 'Zubehör', price: 100, types: ['streaming', 'creator', 'office'], description: '4K USB Webcam mit Autofokus und Weitwinkel-Objektiv. Ideal für Streaming, Videokonferenzen und Content Creation.', affiliateLink: 'https://affiliate.example.com/acc/webcam-4k' },
        { id: 21, name: 'Mikrofon Kondenser USB-C', type: 'Zubehör', price: 80, types: ['streaming', 'creator'], description: 'Professionelles USB-C Kondenser-Mikrofon mit Nierencharakteristik. Liefert Studio-Qualität für Streaming und Podcasting.', affiliateLink: 'https://affiliate.example.com/acc/mic-usb' },
        { id: 22, name: 'PC Ständer/Erhöhung', type: 'Zubehör', price: 45, types: ['gaming', 'office', 'streaming', 'creator', 'workstation', 'budget'], description: 'Robuster PC Ständer mit Kabelmanagement. Verbessert Luftzirkulation und spart Schreibtischplatz.', affiliateLink: 'https://affiliate.example.com/acc/pc-stand' },
    ]
};
