const componentsData = {
    cpus: [
        { id: 1, name: 'Intel Core i9-14900KF', socket: 'LGA1700', tdp: 253, price: 480, types: ['gaming', 'streaming', 'workstation'], affiliateLink: 'https://affiliate.example.com/cpu/i9-14900kf' },
        { id: 2, name: 'Intel Core i9-14900K', socket: 'LGA1700', tdp: 253, price: 520, types: ['gaming', 'streaming', 'workstation'], affiliateLink: 'https://affiliate.example.com/cpu/i9-14900k' },
        { id: 3, name: 'Intel Core i7-14700K', socket: 'LGA1700', tdp: 125, price: 350, types: ['gaming', 'streaming', 'workstation'], affiliateLink: 'https://affiliate.example.com/cpu/i7-14700k' },
        { id: 4, name: 'Intel Core i5-14600K', socket: 'LGA1700', tdp: 125, price: 240, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/cpu/i5-14600k' },
        { id: 5, name: 'Intel Core i5-14600', socket: 'LGA1700', tdp: 65, price: 180, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/cpu/i5-14600' },
        { id: 6, name: 'Intel Core i3-14100', socket: 'LGA1700', tdp: 42, price: 80, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/cpu/i3-14100' },
        { id: 7, name: 'AMD Ryzen 9 7950X3D', socket: 'AM5', tdp: 162, price: 550, types: ['gaming', 'streaming', 'workstation'], affiliateLink: 'https://affiliate.example.com/cpu/ryzen-9-7950x3d' },
        { id: 8, name: 'AMD Ryzen 9 7950X', socket: 'AM5', tdp: 162, price: 480, types: ['gaming', 'streaming', 'workstation'], affiliateLink: 'https://affiliate.example.com/cpu/ryzen-9-7950x' },
        { id: 9, name: 'AMD Ryzen 7 7700X', socket: 'AM5', tdp: 105, price: 280, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/cpu/ryzen-7-7700x' },
        { id: 10, name: 'AMD Ryzen 5 7600X', socket: 'AM5', tdp: 105, price: 160, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/cpu/ryzen-5-7600x' },
        { id: 11, name: 'AMD Ryzen 5 5600X', socket: 'AM4', tdp: 65, price: 150, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/cpu/ryzen-5-5600x' },
        { id: 12, name: 'AMD Ryzen 5 5500', socket: 'AM4', tdp: 65, price: 90, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/cpu/ryzen-5-5500' },
        { id: 13, name: 'Intel Xeon W9-3495X', socket: 'LGA4677', tdp: 350, price: 3200, types: ['workstation'], affiliateLink: 'https://affiliate.example.com/cpu/xeon-w9' },
        { id: 14, name: 'AMD Ryzen Threadripper 7980X', socket: 'TRX40', tdp: 320, price: 3500, types: ['workstation'], affiliateLink: 'https://affiliate.example.com/cpu/threadripper-7980x' },
    ],
    
    mainboards: [
        { id: 1, name: 'ASUS ROG STRIX Z790-E Gaming WiFi', socket: 'LGA1700', ramType: 'DDR5', maxRam: 192, psuType: 'ATX', price: 420, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/mb/z790-e' },
        { id: 2, name: 'MSI MPG Z790 Edge WiFi', socket: 'LGA1700', ramType: 'DDR5', maxRam: 192, psuType: 'ATX', price: 380, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/mb/z790-edge' },
        { id: 3, name: 'ASUS TUF B660-Plus WiFi', socket: 'LGA1700', ramType: 'DDR4', maxRam: 128, psuType: 'ATX', price: 180, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/mb/b660-plus' },
        { id: 4, name: 'ASUS ROG STRIX X870-E Gaming WiFi', socket: 'AM5', ramType: 'DDR5', maxRam: 192, psuType: 'ATX', price: 450, types: ['gaming', 'streaming', 'workstation'], affiliateLink: 'https://affiliate.example.com/mb/x870-e' },
        { id: 5, name: 'MSI MPG B550 Edge WiFi', socket: 'AM4', ramType: 'DDR4', maxRam: 128, psuType: 'ATX', price: 150, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/mb/b550-edge' },
        { id: 6, name: 'ASUS ROG STRIX B550-I Gaming WiFi', socket: 'AM4', ramType: 'DDR4', maxRam: 128, psuType: 'SFX', price: 200, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/mb/b550-i' },
        { id: 7, name: 'Gigabyte B760 AORUS Pro', socket: 'LGA1700', ramType: 'DDR5', maxRam: 192, psuType: 'ATX', price: 200, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/mb/b760-pro' },
        { id: 8, name: 'ASRock B760M Pro RS', socket: 'LGA1700', ramType: 'DDR4', maxRam: 128, psuType: 'Micro-ATX', price: 120, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/mb/b760m-pro' },
        { id: 9, name: 'ASUS TUF X870-E Gaming WiFi', socket: 'AM5', ramType: 'DDR5', maxRam: 192, psuType: 'ATX', price: 480, types: ['gaming', 'workstation'], affiliateLink: 'https://affiliate.example.com/mb/x870-e-tuf' },
        { id: 10, name: 'MSI MPG X870E-E Gaming WiFi', socket: 'AM5', ramType: 'DDR5', maxRam: 192, psuType: 'ATX', price: 470, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/mb/x870e-e' },
    ],
    
    rams: [
        { id: 1, name: 'Corsair Vengeance DDR5 6000MHz 32GB', type: 'DDR5', capacity: 32, speed: 6000, price: 160, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/ram/ddr5-6000-32gb' },
        { id: 2, name: 'Corsair Vengeance DDR5 6000MHz 64GB', type: 'DDR5', capacity: 64, speed: 6000, price: 300, types: ['gaming', 'workstation', 'streaming'], affiliateLink: 'https://affiliate.example.com/ram/ddr5-6000-64gb' },
        { id: 3, name: 'G.Skill Trident Z5 DDR5 6400MHz 64GB', type: 'DDR5', capacity: 64, speed: 6400, price: 320, types: ['gaming', 'workstation', 'streaming'], affiliateLink: 'https://affiliate.example.com/ram/ddr5-6400-64gb' },
        { id: 4, name: 'Kingston Fury DDR5 5600MHz 32GB', type: 'DDR5', capacity: 32, speed: 5600, price: 150, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/ram/ddr5-5600-32gb' },
        { id: 5, name: 'Corsair Vengeance DDR4 3600MHz 32GB', type: 'DDR4', capacity: 32, speed: 3600, price: 110, types: ['gaming', 'office'], affiliateLink: 'https://affiliate.example.com/ram/ddr4-3600-32gb' },
        { id: 6, name: 'G.Skill Flare X DDR4 3200MHz 32GB', type: 'DDR4', capacity: 32, speed: 3200, price: 100, types: ['gaming', 'office', 'budget'], affiliateLink: 'https://affiliate.example.com/ram/ddr4-3200-32gb' },
        { id: 7, name: 'Kingston Fury DDR4 3200MHz 16GB', type: 'DDR4', capacity: 16, speed: 3200, price: 55, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/ram/ddr4-3200-16gb' },
        { id: 8, name: 'Corsair Vengeance DDR4 3200MHz 16GB', type: 'DDR4', capacity: 16, speed: 3200, price: 50, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/ram/ddr4-3200-16gb' },
        { id: 9, name: 'G.Skill Trident Z5 DDR5 7200MHz 48GB', type: 'DDR5', capacity: 48, speed: 7200, price: 280, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/ram/ddr5-7200-48gb' },
    ],
    
    gpus: [
        { id: 1, name: 'NVIDIA RTX 4090', power: 450, length: 375, price: 1600, types: ['gaming', 'streaming', 'workstation'], affiliateLink: 'https://affiliate.example.com/gpu/rtx-4090' },
        { id: 2, name: 'NVIDIA RTX 4080 Super', power: 320, length: 360, price: 1200, types: ['gaming', 'streaming', 'workstation'], affiliateLink: 'https://affiliate.example.com/gpu/rtx-4080s' },
        { id: 3, name: 'NVIDIA RTX 4070 Ti', power: 285, length: 335, price: 900, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/gpu/rtx-4070ti' },
        { id: 4, name: 'NVIDIA RTX 4070', power: 200, length: 310, price: 700, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/gpu/rtx-4070' },
        { id: 5, name: 'NVIDIA RTX 4060 Ti', power: 130, length: 255, price: 380, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/gpu/rtx-4060ti' },
        { id: 6, name: 'NVIDIA RTX 4060', power: 70, length: 240, price: 240, types: ['gaming', 'budget', 'office'], affiliateLink: 'https://affiliate.example.com/gpu/rtx-4060' },
        { id: 7, name: 'AMD Radeon RX 7900 XTX', power: 420, length: 385, price: 1250, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/gpu/rx-7900xtx' },
        { id: 8, name: 'AMD Radeon RX 7900 XT', power: 420, length: 380, price: 800, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/gpu/rx-7900xt' },
        { id: 9, name: 'AMD Radeon RX 7800 XT', power: 320, length: 320, price: 500, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/gpu/rx-7800xt' },
        { id: 10, name: 'AMD Radeon RX 7600', power: 150, length: 280, price: 220, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/gpu/rx-7600' },
        { id: 11, name: 'Intel Arc A770 16GB', power: 225, length: 300, price: 350, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/gpu/arc-a770' },
        { id: 12, name: 'No GPU (iGPU)', power: 0, length: 0, price: 0, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/gpu/no-gpu' },
    ],
    
    psus: [
        { id: 1, name: 'Corsair RM1000x 1000W', wattage: 1000, type: 'ATX', price: 180, types: ['gaming', 'streaming', 'workstation'], affiliateLink: 'https://affiliate.example.com/psu/rm1000x' },
        { id: 2, name: 'Corsair HX1000 1000W', wattage: 1000, type: 'ATX', price: 200, types: ['gaming', 'streaming', 'workstation'], affiliateLink: 'https://affiliate.example.com/psu/hx1000' },
        { id: 3, name: 'MSI MPG A750GF 750W', wattage: 750, type: 'ATX', price: 120, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/psu/a750gf' },
        { id: 4, name: 'EVGA SuperNOVA 850 GA 850W', wattage: 850, type: 'ATX', price: 140, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/psu/850ga' },
        { id: 5, name: 'Seasonic Focus Plus 650W', wattage: 650, type: 'ATX', price: 100, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/psu/focus-650' },
        { id: 6, name: 'Be Quiet! System Power 500W', wattage: 500, type: 'ATX', price: 65, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/psu/bq-500' },
        { id: 7, name: 'Corsair SF750 750W', wattage: 750, type: 'SFX', price: 180, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/psu/sf750' },
        { id: 8, name: 'Silverstone SX500-LG 500W', wattage: 500, type: 'SFX', price: 100, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/psu/sx500-lg' },
        { id: 9, name: 'Gigabyte UD850GM 850W', wattage: 850, type: 'ATX', price: 130, types: ['gaming', 'workstation'], affiliateLink: 'https://affiliate.example.com/psu/ud850gm' },
    ],
    
    storages: [
        { id: 1, name: 'Samsung 990 Pro 2TB NVMe', type: 'NVMe', capacity: 2000, price: 180, types: ['gaming', 'streaming', 'workstation'], affiliateLink: 'https://affiliate.example.com/storage/990pro-2tb' },
        { id: 2, name: 'Samsung 990 Pro 4TB NVMe', type: 'NVMe', capacity: 4000, price: 350, types: ['streaming', 'workstation'], affiliateLink: 'https://affiliate.example.com/storage/990pro-4tb' },
        { id: 3, name: 'WD Black SN850X 1TB', type: 'NVMe', capacity: 1000, price: 120, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/storage/sn850x-1tb' },
        { id: 4, name: 'WD Black SN850X 2TB', type: 'NVMe', capacity: 2000, price: 220, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/storage/sn850x-2tb' },
        { id: 5, name: 'Kingston NV2 1TB', type: 'NVMe', capacity: 1000, price: 80, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/storage/nv2-1tb' },
        { id: 6, name: 'Kingston NV2 2TB', type: 'NVMe', capacity: 2000, price: 150, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/storage/nv2-2tb' },
        { id: 7, name: 'Seagate Barracuda 2TB HDD', type: 'HDD', capacity: 2000, price: 50, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/storage/barracuda-2tb' },
        { id: 8, name: 'WD Blue 1TB HDD', type: 'HDD', capacity: 1000, price: 30, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/storage/blue-1tb' },
        { id: 9, name: 'Samsung 870 EVO 1TB SSD', type: 'SATA', capacity: 1000, price: 70, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/storage/870evo-1tb' },
        { id: 10, name: 'Sabrent Rocket Plus 2TB NVMe', type: 'NVMe', capacity: 2000, price: 140, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/storage/rocket-2tb' },
    ],
    
    cases: [
        { id: 1, name: 'Lian Li O11 Dynamic', maxGpuLength: 420, maxCoolerHeight: 180, psuType: 'ATX', price: 150, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/case/o11-dynamic' },
        { id: 2, name: 'Corsair Crystal 570X RGB', maxGpuLength: 370, maxCoolerHeight: 160, psuType: 'ATX', price: 180, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/case/570x' },
        { id: 3, name: 'NZXT H510 Flow', maxGpuLength: 330, maxCoolerHeight: 165, psuType: 'ATX', price: 110, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/case/h510-flow' },
        { id: 4, name: 'Phanteks Eclipse P500A', maxGpuLength: 330, maxCoolerHeight: 180, psuType: 'ATX', price: 140, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/case/p500a' },
        { id: 5, name: 'Lian Li Q58', maxGpuLength: 280, maxCoolerHeight: 120, psuType: 'SFX', price: 130, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/case/q58' },
        { id: 6, name: 'Corsair Crystal 280X RGB', maxGpuLength: 310, maxCoolerHeight: 150, psuType: 'SFX', price: 150, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/case/280x' },
        { id: 7, name: 'Fractal Design Core 1000', maxGpuLength: 350, maxCoolerHeight: 160, psuType: 'ATX', price: 50, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/case/core1000' },
        { id: 8, name: 'Cooler Master Hyper 212 LED', maxGpuLength: 380, maxCoolerHeight: 180, psuType: 'ATX', price: 85, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/case/hyper212' },
        { id: 9, name: 'Corsair 5000D Airflow', maxGpuLength: 390, maxCoolerHeight: 170, psuType: 'ATX', price: 160, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/case/5000d' },
        { id: 10, name: 'NZXT H710i', maxGpuLength: 370, maxCoolerHeight: 160, psuType: 'ATX', price: 200, types: ['gaming'], affiliateLink: 'https://affiliate.example.com/case/h710i' },
    ],
    
    coolers: [
        { id: 1, name: 'Noctua NH-D15', height: 160, tdpRating: 250, price: 90, types: ['gaming', 'office'], affiliateLink: 'https://affiliate.example.com/cooler/nh-d15' },
        { id: 2, name: 'Be Quiet Dark Rock Pro 4', height: 162, tdpRating: 250, price: 85, types: ['gaming', 'office'], affiliateLink: 'https://affiliate.example.com/cooler/drp4' },
        { id: 3, name: 'Corsair H150i Elite Capellix', height: 120, tdpRating: 300, price: 200, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/cooler/h150i' },
        { id: 4, name: 'NZXT Kraken X93', height: 110, tdpRating: 320, price: 180, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/cooler/kraken-x93' },
        { id: 5, name: 'Thermalright Peerless Assassin 120 SE', height: 155, tdpRating: 280, price: 35, types: ['gaming', 'budget'], affiliateLink: 'https://affiliate.example.com/cooler/pa120se' },
        { id: 6, name: 'Scythe Mugen 5 Rev. B', height: 154, tdpRating: 250, price: 50, types: ['gaming', 'office', 'budget'], affiliateLink: 'https://affiliate.example.com/cooler/mugen5' },
        { id: 7, name: 'Noctua NH-U12S', height: 158, tdpRating: 220, price: 65, types: ['gaming', 'office', 'budget'], affiliateLink: 'https://affiliate.example.com/cooler/nh-u12s' },
        { id: 8, name: 'Corsair H100i Elite Capellix', height: 115, tdpRating: 240, price: 150, types: ['gaming', 'streaming'], affiliateLink: 'https://affiliate.example.com/cooler/h100i' },
        { id: 9, name: 'Be Quiet Dark Rock 4', height: 159, tdpRating: 200, price: 65, types: ['office', 'budget'], affiliateLink: 'https://affiliate.example.com/cooler/dr4' },
    ],
    
    preBuiltPCs: [
        { id: 1, name: '💼 Office PC', description: 'Ideal für Office-Arbeit und Videokonferenzen', price: 800, type: 'office', affiliateLink: 'https://affiliate.example.com/pc/office' },
        { id: 2, name: '🎮 Gaming PC (1440p)', description: '1440p Gaming mit hohen FPS', price: 2500, type: 'gaming', affiliateLink: 'https://affiliate.example.com/pc/gaming' },
        { id: 3, name: '🎥 Streaming PC', description: '4K Streaming und Content Creation', price: 3500, type: 'streaming', affiliateLink: 'https://affiliate.example.com/pc/streaming' },
        { id: 4, name: '🖥️ Workstation', description: '3D Rendering und Video Editing', price: 4500, type: 'workstation', affiliateLink: 'https://affiliate.example.com/pc/workstation' },
        { id: 5, name: '⚡ Budget Gaming', description: '1080p Gaming für Einsteiger', price: 1200, type: 'budget', affiliateLink: 'https://affiliate.example.com/pc/budget' },
        { id: 6, name: '🚀 High-End Gaming', description: '4K Gaming Ultra Settings', price: 5000, type: 'gaming', affiliateLink: 'https://affiliate.example.com/pc/highend' }
    ]
};
